name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Rush install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --verbose
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Rush test
        run: node common/scripts/install-run-rush.js test
      - name: Upload Playwright report - simple-form-jou
        uses: actions/upload-artifact@v4
        if: ${{ ! cancelled() }} # Ensures artifacts upload even on failure
        with:
          name: playwright-report-simple-form-joy
          path: packages/simple-form-joy/playwright-report/
          retention-days: 30
      - name: Rush eslint
        run: node common/scripts/install-run-rush.js eslint
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
